on: workflow_dispatch
name: Manual broken link check

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken link check
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
          recursive: true

      - name: Send notification
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repoOwner = '${{ github.repository_owner }}';
            const repoName = '${{ github.event.repository.name }}';
            const jobStatus = '${{ job.status }}';

            const message = `Broken link check for ${repoOwner}/${repoName} completed with status: ${jobStatus}`;

            github.issues.createComment({
              owner: repoOwner,
              repo: repoName,
              issue_number: context.issue.number,
              body: message
            });